import type { Work } from '@/lib/types';

export const works: Work[] = [
  {
    id: '1',
    slug: 'dongsuh-mitte-imc-2024',
    title: '동서 미떼 2024년 IMC 캠페인',
    client: '동서식품',
    category: 'IMC',
    thumbnail_url: '/work/placeholder.svg',
    description: '동서 미떼 브랜드의 통합 마케팅 커뮤니케이션 캠페인. 온·오프라인 채널을 아우르는 브랜드 경험을 설계했습니다.',
    year: 2024,
    sort_order: 1,
    published: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'hyundai-sonata-imc-2021',
    title: '현대자동차 쏘나타 센슈어스 캠페인',
    client: '현대자동차',
    category: 'IMC',
    thumbnail_url: '/work/placeholder.svg',
    description: '2021 쏘나타 센슈어스의 브랜드 아이덴티티를 강화하는 통합 캠페인. 감성적 메시지와 디지털 채널을 결합했습니다.',
    year: 2021,
    sort_order: 2,
    published: true,
    created_at: '2021-03-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'kb-rise-etf-launch-2024',
    title: 'KB자산운용 RISE ETF 런칭 영상 캠페인',
    client: 'KB자산운용',
    category: '런칭',
    thumbnail_url: '/work/placeholder.svg',
    description: 'RISE ETF 신규 브랜드의 시장 진입을 위한 런칭 영상 캠페인. 투자자 타깃 핵심 메시지를 직관적으로 전달했습니다.',
    year: 2024,
    sort_order: 3,
    published: true,
    created_at: '2024-03-01T00:00:00Z',
  },
  {
    id: '4',
    slug: 'ringle-launch-2021',
    title: '링글 I\'m a Ringler 런칭 캠페인',
    client: '링글',
    category: '런칭',
    thumbnail_url: '/work/placeholder.svg',
    description: '영어 화상 튜터링 플랫폼 링글의 브랜드 런칭 캠페인. 타깃 페르소나 기반의 스토리텔링으로 브랜드 인지도를 구축했습니다.',
    year: 2021,
    sort_order: 4,
    published: true,
    created_at: '2021-06-01T00:00:00Z',
  },
  {
    id: '5',
    slug: 'hite-filite-instatoon',
    title: '하이트진로 필라이트 언필리버블 인스타툰',
    client: '하이트진로',
    category: 'Issue-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '필라이트의 독창적인 세계관을 인스타툰으로 구현한 이슈업 캠페인. SNS 바이럴로 브랜드 화제성을 극대화했습니다.',
    year: 2022,
    sort_order: 5,
    published: true,
    created_at: '2022-05-01T00:00:00Z',
  },
  {
    id: '6',
    slug: 'oliveyoung-padeparfait-2021',
    title: '올리브영 매일 다른 날 위한 오늘파데',
    client: '올리브영',
    category: 'Issue-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '올리브영 파운데이션 카테고리의 브랜드 이슈업 캠페인. 일상 속 다양한 피부 고민을 공감 콘텐츠로 연결했습니다.',
    year: 2021,
    sort_order: 6,
    published: true,
    created_at: '2021-09-01T00:00:00Z',
  },
  {
    id: '7',
    slug: 'sony-performance-2024',
    title: '소니 2023~2024년 퍼포먼스 캠페인',
    client: '소니코리아',
    category: 'Sales-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '소니코리아 주요 제품군의 데이터 기반 퍼포먼스 마케팅 캠페인. 정밀 타겟팅으로 전환율과 ROI를 극대화했습니다.',
    year: 2024,
    sort_order: 7,
    published: true,
    created_at: '2023-09-01T00:00:00Z',
  },
  {
    id: '8',
    slug: 'aimvita-student-2023',
    title: '아임비타 수험생 응원 캠페인',
    client: '아임비타',
    category: 'Sales-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '수능 시즌 수험생을 타겟으로 한 아임비타 Sales-up 캠페인. 공감 메시지와 프로모션을 결합해 매출 성장을 이끌었습니다.',
    year: 2023,
    sort_order: 8,
    published: true,
    created_at: '2023-10-01T00:00:00Z',
  },
];
