import type { Work } from '@/lib/types';

export const works: Work[] = [
  {
    id: '1',
    slug: 'imc-brand-launch-2024',
    title: '브랜드 통합 커뮤니케이션 캠페인',
    client: '클라이언트 A',
    category: 'IMC',
    thumbnail_url: '/work/placeholder.svg',
    description: '브랜드 아이덴티티를 강화하는 통합 마케팅 커뮤니케이션 캠페인',
    year: 2024,
    sort_order: 1,
    published: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'new-product-launch-2024',
    title: '신제품 런칭 캠페인',
    client: '클라이언트 B',
    category: '런칭',
    thumbnail_url: '/work/placeholder.svg',
    description: '혁신적인 신제품의 시장 진입을 위한 런칭 캠페인',
    year: 2024,
    sort_order: 2,
    published: true,
    created_at: '2024-02-01T00:00:00Z',
  },
  {
    id: '3',
    slug: 'issue-up-social-2023',
    title: '소셜 이슈업 캠페인',
    client: '클라이언트 C',
    category: 'Issue-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '브랜드 이슈를 소셜 미디어를 통해 증폭시킨 캠페인',
    year: 2023,
    sort_order: 3,
    published: true,
    created_at: '2023-06-01T00:00:00Z',
  },
  {
    id: '4',
    slug: 'sales-up-promotion-2023',
    title: '매출 증대 프로모션',
    client: '클라이언트 D',
    category: 'Sales-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '데이터 기반 타겟팅으로 매출을 극대화한 프로모션 캠페인',
    year: 2023,
    sort_order: 4,
    published: true,
    created_at: '2023-09-01T00:00:00Z',
  },
  {
    id: '5',
    slug: 'integrated-campaign-2023',
    title: '통합 브랜드 캠페인',
    client: '클라이언트 E',
    category: 'IMC',
    thumbnail_url: '/work/placeholder.svg',
    description: 'On/Off 채널을 아우르는 통합 브랜드 경험 캠페인',
    year: 2023,
    sort_order: 5,
    published: true,
    created_at: '2023-03-01T00:00:00Z',
  },
  {
    id: '6',
    slug: 'brand-relaunch-2022',
    title: '브랜드 리런칭 캠페인',
    client: '클라이언트 F',
    category: '런칭',
    thumbnail_url: '/work/placeholder.svg',
    description: '브랜드 리포지셔닝을 위한 리런칭 캠페인',
    year: 2022,
    sort_order: 6,
    published: true,
    created_at: '2022-07-01T00:00:00Z',
  },
  {
    id: '7',
    slug: 'viral-issue-2022',
    title: '바이럴 이슈 캠페인',
    client: '클라이언트 G',
    category: 'Issue-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '창의적인 아이디어로 바이럴을 이끌어낸 이슈업 캠페인',
    year: 2022,
    sort_order: 7,
    published: true,
    created_at: '2022-04-01T00:00:00Z',
  },
  {
    id: '8',
    slug: 'performance-sales-2022',
    title: '퍼포먼스 마케팅 캠페인',
    client: '클라이언트 H',
    category: 'Sales-up',
    thumbnail_url: '/work/placeholder.svg',
    description: '데이터 분석 기반의 퍼포먼스 마케팅으로 ROI를 극대화한 캠페인',
    year: 2022,
    sort_order: 8,
    published: true,
    created_at: '2022-01-01T00:00:00Z',
  },
];
